### ISSUE TITLE
Logout and relogging in bug

### ISSUE THREAD

**Issue by jupiter0107** [chat-sdk/chat-sdk-ios#193]
Hello , 

There seems to be a problem with the app whenever a user logs out and logs in again (without killing the application) 

To recreate the issue, 
1) Log into the app
2) Log out without killing the application 
3) log in again 

Problems that arises 
1) The cells on the privateThreadsViewController (conversations tab) appears to be missing, until the user refreshes the tab by selecting a different tab to reselect it again. eg: Click Profile tab -> Click Conversations tab. 
2) Unable to search for any user to add as friend on the searchViewController
3) Messages that are sent during this session is not captured on firebase / received by partner.

**Comment by bensmiley** [comment]
Fixed awaiting release 4.3.16.

**Comment by jupiter0107** [comment]
@bensmiley Hi ben, however this fix only shows the cells, Issues 2 and 3 still persists.  
The messages that are being sent are still not captured on firebase

**Comment by jupiter0107** [comment]
Hello @bensmiley  any updates on this?
