### ISSUE TITLE
ChatSDK Leave thread issue

### ISSUE THREAD

**Issue by vineethsreekumar** [chat-sdk/chat-sdk-ios#497]
1. Is the bug present in the demo Chat SDK project? - Yes
2. What modifications have you made to the Chat SDK? -  Leave thread function  call
3. iOS Version? Device or simulator? - Simulator iPhone 13 pro max
4. Steps taken to reproduce the problem: call leave thread BChatSDK.thread().leave(thread) - current user to leave the thread in a group
5. Expected result: leave the group
6. Actual result: Error Domain=RXPromise Code=-1000 "" UserInfo={NSLocalizedFailureReason=}
7. Comments:

**Comment by vineethsreekumar** [comment]
@bensmiley Updated here

**Comment by vineethsreekumar** [comment]
Can we leave a user in a group ? BChatSDK.thread().leave(thread) function ?

**Comment by bensmiley** [comment]
This has been resolved. Please check out the latest version of the project.

**Comment by vineethsreekumar** [comment]
@bensmiley Tried the latest version 5.0.11 and the issue still exist.

**Comment by bensmiley** [comment]
You need to check out the version from Github.

**Comment by vineethsreekumar** [comment]
which version? I did pod install .

**Comment by bensmiley** [comment]
From **Github** not **Cocoapods** you need to add the project as a development pod... because it's not released yet on Cocoapods.

**Comment by vineethsreekumar** [comment]
these are the pods what I am using from chat SDK
pod "ChatSDK/UI"
pod "ChatSDKFirebase/Adapter"
pod "ChatSDKFirebase/Upload"
pod "ChatSDKFirebase/Push"
pod "ChatSDKFirebase/FirebaseUI"

How I should use it now?

**Comment by bensmiley** [comment]
Here's an example: 

https://github.com/chat-sdk/chat-sdk-ios/blob/master/DemoSwift/Podfile

https://stackoverflow.com/questions/59199431/what-is-a-development-pod

**Comment by vineethsreekumar** [comment]
@bensmiley  Hi Ben when will be your new release with these fixes ?
