### ISSUE TITLE
Inaccurate day ago label after passing midnight

### ISSUE THREAD

**Issue by CalvinTp** [chat-sdk/chat-sdk-ios#61]
Hi,
Seems like there is an issue related on the day ago label (in the dateAgo method) which has "Today", "Yesterday", "Date/Year" calculation. 

If you send message A at 11.30pm and message B at 12.30am, in the BChatViewController, the message A should be labelled as "Yesterday" and message B should be labelled as "Today"; but both are currently labeled as "Today". 

```
    if ([self daysAgo] == 0) {
        day = [NSBundle t: bToday];
    }
    else if ([self daysAgo] == 1) {
        day = [NSBundle t: bYesterday];
    }
    else if (self.daysAgo < 7) {
        [formatter setDateFormat:@"EEE"];
        day = [formatter stringFromDate:self];
    }
    else {
        [formatter setDateFormat:@"MM/yy"];
        day = [formatter stringFromDate:self];
    }
```

Thanks,
Calvin

**Comment by CalvinTp** [comment]
Hi,
After debugging, the issue is due to the timezone differences. 

Below is the NSLog which I have added inside the BMessageCell.m file. I am curious why does printing out the hour and minutes seems to work but the "Today", "Yesterday" in the section header seems to  fail. 

The code below print out the format of the message before and after the format conversion: 

```
    if (message.flagged.intValue) {
        _timeLabel.text = [NSBundle t:bFlagged];
    }

    NSLog(@"BMessageCell.setMessage:withColorWeight -> _message.textString:%@",_message.textString);
    NSLog(@"BMessageCell.setMessage:withColorWeight -> _message.date:%@",_message.date);
    NSLog(@"BMessageCell.setMessage:withColorWeight -> _message.date.messageTimeAt:%@",_message.date.messageTimeAt);
    
    _timeLabel.text = _message.date.messageTimeAt;
```

The output of the NSLog is shown as below:

```
2017-05-30 03:22:04.404 ChatSDK Demo[8128:3775298] BMessageCell.setMessage:withColorWeight -> _message.textString:Ybkdjd
2017-05-30 03:22:04.404 ChatSDK Demo[8128:3775298] BMessageCell.setMessage:withColorWeight -> _message.date:2017-05-29 17:19:10 +0000
2017-05-30 03:22:04.405 ChatSDK Demo[8128:3775298] BMessageCell.setMessage:withColorWeight -> _message.date.messageTimeAt:30/May 01:19
```

The result clearly shows that the date is stored in "+0000" timezone. This is an issue because at local time, the message is already sent pass midnight, but at "+0000" timezone the time has yet to passed midnight yet (so it is still counted as today). 

Therefore for the section header to work properly, it needs to be formatted into the local timezone first before it can be used, else the ChatViewController will shows an incorrect section header for "Today", "Yesterday", and the dates.  


Thanks,
Calvin

**Comment by simonsmiley64** [comment]
Hi @CalvinTp,

This is an issue which is currently on our to do list. Currently we are extremely busy with upgrading the Chat SDK so will not have time to implement this modification for now. 

If this is something you feel is important for your project using Chat SDK it would be great if you could look into setting the time zones and then create a pull request. 

I remember looking back at this a while ago and finding it a tricky piece of code to get it working in all scenarios:

+ Need to look at what the current time is
+ Need to look at which timezone we are in
+ Need to look at what time the message was sent (and what timezone)
+ Need to look at whether a midnight falls between the message time and the current time

All the while we need to check the time and know which timezone the message was sent in and the one we are in. I would recommend the following approach:

+ Always store the time in (+0000) timezone. This will mean all the messages are on the same frame of reference
+ When we look at the time convert it into the current users timezone, check the different and add the additional time
+ Do this with both times (current user time and message time)
+ We can now compare the times and see if a midnight falls between them and then configure the time label from there.

The important part here is always having the +0000 frame of reference to work with.

If you do get time to do any work on this then it would be great to submit a pull request and we can then test it and look at adding it to the code,

Keep up the good work 👍

Simon

**Comment by CalvinTp** [comment]
Hi Simon,
No worries, the iOS codes are great. I do noticed a number of enhancements while reading the codes. 

Yes, this is not really an important issue and I think have solved this issue at my side. Yes, you have looked into similar issue previously however this is a different because the issue is on the algorithm to generate the sections in the ChatViewController. Since the sections are calculated using +0000 timezone, i have added the codes to factored them into local time before calculation. The message cell displayed will be formatted into local time as well. 

I would perhaps paste you the codes so that you can merge it to solve this or probably do a pull request next week as I am tied up this week. 

Looking forward to get more great codes from you guys! 

Thanks,
Calvin

**Comment by bensmiley** [comment]
Fixed in 4.3.7.

**Comment by ChintanWeapp** [comment]
![screen shot 2018-05-11 at 12 29 51 pm](https://user-images.githubusercontent.com/34238752/39910941-1d58401c-5517-11e8-81cd-4c4d0a29d9ce.png)

I'am still getting "Today" label as in all the Sections in my chat view. Where the chats are from different date. How to resolve this?
